### ISSUE TITLE
[Redux] Server side rendering React with Redux

### ISSUE THREAD

**Issue by artemidas** [remarkablemark/tutorials#5]
React Redux server side rendering explained.

Link to the [official docs](http://redux.js.org/docs/recipes/ServerRendering.html)

**Comment by remarkablemark** [comment]
Thanks @Artemidas for the tutorial request!

I'll try to work on it after I get some parts done for #1. Thanks for being patient.

**Comment by remarkablemark** [comment]
I have a working version in the [redux](https://github.com/remarkablemark/universal-react-tutorial/tree/v7) branch. You can view the [diff](https://github.com/remarkablemark/universal-react-tutorial/compare/v6...v7) to see what I added.

It's very minimal at the moment (reducer doesn't do anything except return default state and no actions).

I'll try to make time in the next few days to do the recordings. You can keep track of my progress [here](https://github.com/remarkablemark/tutorials/projects/1).

**Comment by artemidas** [comment]
Thanks! The code looks nice, can't wait to see some videos :)

**Comment by remarkablemark** [comment]
@Artemidas The [video](https://b.remarkabl.org/2hybtYR) has been published!
